import base64
import io
import json
import logging
import os
import random
import textwrap
from typing import List
import os
from itertools import cycle

import cv2
import numpy as np
from google import genai
from google.genai import types
from openai import OpenAI
from PIL import Image, ImageDraw, ImageFont

from agents.structs import FrameData, GameAction, GameState
from agents.templates.reasoning_agent import ReasoningLLM

logger = logging.getLogger(__name__)

TOP_HYPOTHESIS_RETRIEVER_PROMPT = """You are a top hypothesis retriever for the game.

The game is designed based on below Constraints
- Easy for humans (can pick it up in <1 min of game play)
- Core Knowledge Priors (no language, trivia, cultural symbols)
- Should require no instructions to play
- Should be fun for humans and playable in 5-10 minutes
- Innovative and novel game mechanics encouraged (Hidden state, theory of mind, long term planning, navigating other agents, etc.)

Here are the hypotheses generated by random analysis

{all_random_hypothesis_text}

Pick only 1 valuable Multi-Stage Delivery hypothesis with significant win impact on the game.

Include element names, description, and approximate size, colors, and shape in the hypothesis. keep the hypothesis targeting with "focusing element names" and "final goal". Also remove unsure sentences from the hypothesis.

Hypothesis: """

RANDOM_HYPOTHESIS_ANALYSIS_PROMPT = """This video is a random actions (WASD and click) moves taken on unkown game.

The game is designed based on below Constraints
- Easy for humans (can pick it up in <1 min of game play)
- Core Knowledge Priors (no language, trivia, cultural symbols)
- Should require no instructions to play
- Should be fun for humans and playable in 5-10 minutes
- Innovative and novel game mechanics encouraged (Hidden state, theory of mind, long term planning, navigating other agents, etc.)

Here are the actions that your player can take
W: Move Up
A: Move Left
S: Move Down
D: Move Right
(x,y): Click on the area by giving x,y space (x: <0, 63>, y: <0, 63>)
Sometimes, some actions has no effect. 

- Write hypothesis clearly with element names clearly
- Keep the hypothesis targeting with "focusing element names" and "final goal". Also remove unsure sentences from the hypothesis."
- element name must be clearly mentioned with approximate size, colors and shape. [Example: (16x15grid)Red_Square_Block]

Give 10 hypothesise to explore the game and understand its mechanics, objectives, and challenges. 
"""

GOAL_ACHIEVEMENT_CHECK_PROMPT = """Given the goal below and the two images (before and after), determine whether the goal has been achieved.

Goal:
{current_goal}

Answer: Just say Yes or No."""


NEXT_ACTION_GENERATOR_PROMPT = """You are an game play next action generator.

Your goal is to generate a single play action to navigate to achieve

{current_goal}

The game which is designed is based on

- Easy for humans (can pick it up in <1 min of game play)
- Core Knowledge Priors (no language, trivia, cultural symbols)
- Should require no instructions to play
- Should be fun for humans and playable in 5-10 minutes
- Innovative and novel game mechanics encouraged (Hidden state, theory of mind, long term planning, navigating other agents, etc.)


Here are the actions that you can generate. The game is fully controlled by below actions:
W: Move Up
A: Move Left
S: Move Down
D: Move Right
CLICK(x,y): Click on the area by giving x,y space (x: <0, 63>, y: <0, 63>)
Sometimes, some actions has no effect. 

Hints:

{hints}
-----

<previous_actions>
The previous action "{previous_action_text}" had {game_effect_flag} effect in the game.

Previous reason: {previous_action_reason}

Re-evaluate the situation to determine which move is better.
<previous_actions>

------

 What can be next action

Your output should be json with action

Example json output:

{{
"action": "W",
"reason": "I need to move up"
}}

"""

current_goal = "You need to move the \"Orange-Capped Blue Block (6x7)\" to the target \"8x7Grid_BlackHead_BlueEye_WhiteSnout\""
hints = """- The Orange-Capped Blue Block (6x7) is the only movable object until now.
- Click action has no visible effect until now
"""
previous_action_text = "A"
previous_action_reason = "The Orange-Capped Blue Block is currently to the right of its target, the '8x7Grid_BlackHead_BlueEye_WhiteSnout'. Continuing to move left ('A') will bring it closer horizontally to the desired position within the larger grey shape."


class CustomReasoningAgent(ReasoningLLM):
    MODEL = "gemini-2.5-pro"
    MAX_ACTIONS = 500
    NEXT_ACTION_GENERATOR_MODEL = "gemini-2.5-pro"
    GOAL_ACHIEVEMENT_CHECK_MODEL = "gemini-2.5-pro"
    RANDOM_ANALYSIS_MODEL = "gemini-2.5-pro"
    TOP_HYPOTHESIS_GENERATOR_MODEL = "gemini-2.5-pro"
    RANDOM_ACTION_MAX_LIMIT = 300
    RANDOM_ANALYSIS_FPS = 10
    RANDOM_ANALYSIS_SKIP_REPEATED_FRAMES_FLAG = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Collect all available shared API keys
        api_keys = list(filter(None, [
            os.getenv("GEMINI_API_KEY"),
            os.getenv("GEMINI_API_KEY_1"),
            os.getenv("GEMINI_API_KEY_2"),
        ]))

        if not api_keys:
            raise ValueError("No valid GEMINI_API_KEYs found in environment variables.")

        # Initialize OpenAI clients
        self._openai_clients = [
            OpenAI(api_key=key, base_url="https://generativelanguage.googleapis.com/v1beta/openai/")
            for key in api_keys
        ]

        # Initialize Gemini clients
        self._gemini_clients = [
            genai.Client(api_key=key)
            for key in api_keys
        ]

        # Create round-robin iterators
        self._openai_cycle = cycle(self._openai_clients)
        self._gemini_cycle = cycle(self._gemini_clients)

        self.current_goal = ""
        self.hints = ""
        self.previous_action_text = "RESET"
        self.previous_action_reason = "Game has been reset."

        # self.current_goal = current_goal
        self.hints = hints

        # Trial/Real run support
        self.trial_runs: List[List[FrameData]] = []
        self.real_runs: List[List[FrameData]] = []
        self.win_runs: List[List[FrameData]] = []

        self.current_trial_run: List[FrameData] = []
        self.current_real_run: List[FrameData] = []

        self.trial_mode: bool = True
        self._last_trial_mode: bool = self.trial_mode
        self._random_action_count: int = 0

    @property
    def client(self):
        """Next OpenAI client (round-robin)."""
        return next(self._openai_cycle)

    @property
    def gemini_client(self):
        """Next Gemini client (round-robin)."""
        return next(self._gemini_cycle)

    @property
    def name(self) -> str:
        return f"{super().name}.{self.MODEL}"

    def is_done(self, frames: List[FrameData], latest_frame: FrameData) -> bool:
        return latest_frame.state == GameState.WIN

    def choose_random_action(
        self, frames: list[FrameData], latest_frame: FrameData
    ) -> GameAction:
        if latest_frame.state in [GameState.NOT_PLAYED, GameState.GAME_OVER]:
            return GameAction.RESET

        action = random.choice([a for a in GameAction if a is not GameAction.RESET])

        if action.is_complex():
            action.set_data(
                {
                    "x": random.randint(0, 63),
                    "y": random.randint(0, 63),
                }
            )
        action.reasoning = {
            "desired_action": f"{action.value}",
            "reason": "Randomly chosen action"
        }
        return action
    def check_game_win(self, frames: List[FrameData], latest_frame: FrameData) -> bool:
        """Check if the game is won based on the latest frame and previous frames."""
        if len(frames) > 1 and frames[-2].score != latest_frame.score:
            return True
        return False

    def generate_hints_from_win_run(self) -> None:
        """Generate hints from the lst win run"""
        logger.info("Generating hints from win run...")
        if not self.win_runs:
            logger.warning("No win runs available to generate hints.")
            return
        last_win_run = self.win_runs[-1]
        if not last_win_run:
            logger.warning("Last win run is empty, cannot generate hints.")
            return
        # Generate hints based on the last win run
        # This is a placeholder for actual hint generation logic

        pass

    def choose_action(
        self, frames: List[FrameData], latest_frame: FrameData
    ) -> GameAction:
        if latest_frame.state in [GameState.NOT_PLAYED]:
            return GameAction.RESET

        self.append_to_current_run(latest_frame)

        # BUG: If the game is won in trail mode, it is generating two hints
        # If reset is clicked, game is full reset, goes to score 0
        # there can be many frames inside single framedata
        # for example, if the game is won, it can have multiple frames with same score
        # Alos, game is reseting is done(goes to score 0) if first move is RESET move is done if in new level
        # if first move is some other, two times reset is clicked, it will reset the game(goes to score 0)
        # TODO: if game goes to 0, need to replay all the win runs, we should not make this one
        if self.check_game_win(frames, latest_frame):
            current_run = self.get_current_run()
            self.win_runs.append(current_run[:])
            self.save_and_reset_current_run()
            # TODO: Do win analysis and provide hints and also track all hints
            self.generate_hints_from_win_run()
            self.trial_mode = True
            # TODO: Need to handle if the game is won in trial mode
            logger.info(f"Game won! Resetting to trial mode. Current run: {len(current_run)} frames.")
            return GameAction.RESET
    
        if self.trial_mode != self._last_trial_mode:
            return self.handle_mode_switch(latest_frame)

        if self.trial_mode:
            # if random action(check previous frame and current frame) has no effect, don't increase the count
            if self.RANDOM_ANALYSIS_SKIP_REPEATED_FRAMES_FLAG and len(frames) > 1 and self.is_frames_equal(frames[-2], latest_frame):
                logger.info("No game effect detected, reducing random action count.")
                self._random_action_count -= 1
            if self._random_action_count < self.RANDOM_ACTION_MAX_LIMIT:
                self._random_action_count += 1
                action = self.choose_random_action(frames, latest_frame)
            if self._random_action_count >= self.RANDOM_ACTION_MAX_LIMIT:
                logger.info(
                    f"Random action limit reached: {self._random_action_count}. Switching to goal-based reasoning."
                )
                self.trial_mode = False
            return action


        is_goal_achieved_flag, goal_achievement_check_output = self.is_goal_achieved(
            previous_frame=frames[-2] if len(frames) > 1 else latest_frame,
            current_frame=latest_frame,
        )
        # Invoke the custom decision logic
        action = self.generate_next_action(latest_frame)
        reasoning = action.reasoning or {}
        reasoning["goal_achievement_check_output"] = goal_achievement_check_output
        reasoning["is_goal_achieved"] = is_goal_achieved_flag
        self.previous_action_text = self.convert_game_action_to_text(action)
        self.previous_action_reason = action.reasoning.get("reason", "No specific reason provided")

        return action

    def handle_mode_switch(self, latest_frame: FrameData) -> GameAction:
        self.append_to_current_run(latest_frame)
        self.save_and_reset_current_run()
        logger.info(f"_last_trial_mode: {self._last_trial_mode}, trial_mode: {self.trial_mode}")
        if self._last_trial_mode and not self.trial_mode:
            logger.info(
                f"Switching from trial mode to real mode. Trial runs: {len(self.trial_runs)}, Real runs: {len(self.real_runs)}"
            )
            all_random_hypothesis_text = self.do_random_hypothesis_analysis(self.trial_runs[-1])
            self.current_goal = self.retrieve_top_hypothesis(all_random_hypothesis_text)
            
        self._last_trial_mode = self.trial_mode
        return GameAction.RESET

    def append_to_current_run(self, latest_frame: FrameData) -> None:
        if self.trial_mode:
            self.current_trial_run.append(latest_frame)
        else:
            self.current_real_run.append(latest_frame)

    def get_current_run(self) -> List[FrameData]:
        if self.trial_mode:
            return self.current_trial_run
        else:
            return self.current_real_run

    def save_and_reset_current_run(self) -> None:
        if self._last_trial_mode and self.current_trial_run:
            self.trial_runs.append(self.current_trial_run[:])
            self.current_trial_run.clear()
        elif not self._last_trial_mode and self.current_real_run:
            self.real_runs.append(self.current_real_run[:])
            self.current_real_run.clear()

    def is_goal_achieved(
        self, previous_frame: FrameData, current_frame: FrameData
    ):
        previous_grid = previous_frame.frame[0] if previous_frame.frame else []
        previous_map_image = self.generate_grid_image_with_zone(previous_grid)
        previous_image_b64 = base64.b64encode(previous_map_image).decode()

        current_grid = current_frame.frame[0] if current_frame.frame else []
        current_map_image = self.generate_grid_image_with_zone(current_grid)
        current_image_b64 = base64.b64encode(current_map_image).decode()

        prompt = GOAL_ACHIEVEMENT_CHECK_PROMPT.format(
            current_goal=self.current_goal,
        )
        
        messages = [
            {
                "role": "system",
                "content": prompt,
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{previous_image_b64}",
                            "detail": "high",
                        },
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{current_image_b64}",
                            "detail": "high",
                        },
                    },
                ],
            }
        ]
        response = self.client.chat.completions.create(
                model=self.GOAL_ACHIEVEMENT_CHECK_MODEL,
                messages=messages,
                # reasoning_effort="low",
                temperature=0.01,
        )
        self.track_tokens(
            response.usage.total_tokens, response.choices[0].message.content
        )
        self.capture_reasoning_from_response(response)

        response_message_text = response.choices[0].message.content
        response_message_text = response_message_text.lower()
        logger.info(f"Response: {response_message_text}")
        if "yes" in response_message_text:
            response_flag = True
        elif "no" in response_message_text:
            response_flag = False
        else:
            logger.error(f"Unexpected response: {response_message_text}")
            response_flag = False

        return response_flag, response.choices[0].message.content

    def is_frames_equal(
        self, previous_frame: FrameData, current_frame: FrameData
    ) -> bool:
        """Check if two frames are equal."""
        if not previous_frame or not current_frame:
            return False
        if not previous_frame.frame or not current_frame.frame:
            return False
        previous_grid = previous_frame.frame[0]
        current_grid = current_frame.frame[0]
        if len(previous_grid) != len(current_grid):
            return False
        for row_prev, row_curr in zip(previous_grid, current_grid):
            if row_prev != row_curr:
                return False
        return True

    def generate_next_action(
        self,
        latest_frame: FrameData,
    ) -> GameAction:
        """Generate the next action based on the current goal and previous action."""
        current_run = self.get_current_run()
        previous_frame = current_run[-2] if len(current_run) > 1 else latest_frame

        if self.is_frames_equal(previous_frame, latest_frame):
            game_effect_flag = "no"
        else:
            game_effect_flag = "some"
        prompt = NEXT_ACTION_GENERATOR_PROMPT.format(
            current_goal=self.current_goal,
            hints=textwrap.fill(hints, width=80),
            previous_action_text=self.previous_action_text,
            previous_action_reason=self.previous_action_reason,
            game_effect_flag=game_effect_flag,
        )
        latest_grid = latest_frame.frame[0] if latest_frame.frame else []
        latest_map_image = self.generate_grid_image_with_zone(latest_grid)
        latest_image_b64 = base64.b64encode(latest_map_image).decode()

        messages = [
            {
                "role": "system",
                "content": prompt,
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{latest_image_b64}",
                            "detail": "high",
                        },
                    }
                ],
            }
        ]

        response = self.client.chat.completions.create(
            model=self.NEXT_ACTION_GENERATOR_MODEL,
            messages=messages,
            # reasoning_effort="low",
        )
        self.track_tokens(
            response.usage.total_tokens, response.choices[0].message.content
        )
        
        response_message_text = response.choices[0].message.content.strip()
        response_message_text = response_message_text.removeprefix("```json")
        response_message_text = response_message_text.removesuffix("```")
        response_message_text = response_message_text.strip()
        logger.info(f"Next action response: {response_message_text}")

        try:
            action_data = json.loads(response_message_text)
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse next action response: {e}")
            action_data = {"action": "UNKNOWN", "reason": "Failed to parse response"}
        return self.convert_action_text_to_game_action(
            action_text=action_data.get("action", ""),
            reason=action_data.get("reason", "")
        )
    
    
    def generate_grid_image_with_zone(
        self, grid: List[List[int]], cell_size: int = 40, zone_size: int = 20
    ) -> bytes:
        """Generate PIL image of the grid with colored cells and zone coordinates."""
        if not grid or not grid[0]:
            # Create empty image
            img = Image.new("RGB", (200, 200), color="black")
            buffer = io.BytesIO()
            img.save(buffer, format="PNG")
            return buffer.getvalue()

        height = len(grid)
        width = len(grid[0])

        # Create image
        img = Image.new("RGB", (width * cell_size, height * cell_size), color="white")
        draw = ImageDraw.Draw(img)

        # Color mapping for grid cells
        key_colors = {
            0: "#FFFFFF",
            1: "#CCCCCC",
            2: "#999999",
            3: "#666666",
            4: "#333333",
            5: "#000000",
            6: "#E53AA3",
            7: "#FF7BCC",
            8: "#F93C31",
            9: "#1E93FF",
            10: "#88D8F1",
            11: "#FFDC00",
            12: "#FF851B",
            13: "#921231",
            14: "#4FCC30",
            15: "#A356D6"
        }

        # Draw grid cells
        for y in range(height):
            for x in range(width):
                color = key_colors.get(grid[y][x], "#888888")  # default: floor

                # Draw cell
                draw.rectangle(
                    [
                        x * cell_size,
                        y * cell_size,
                        (x + 1) * cell_size,
                        (y + 1) * cell_size,
                    ],
                    fill=color,
                    outline="#000000",
                    width=1,
                )

        # Draw zone coordinates and borders
        for y in range(0, height, zone_size):
            for x in range(0, width, zone_size):
                # Draw zone coordinate label
                try:
                    font = ImageFont.load_default()
                    zone_text = f"({x},{y})"
                    draw.text(
                        (x * cell_size + 2, y * cell_size + 2),
                        zone_text,
                        fill="#FFFFFF",
                        font=font,
                    )
                except (ImportError, OSError) as e:
                    logger.debug(f"Could not load font for zone labels: {e}")
                except Exception as e:
                    logger.error(f"Failed to draw zone label at ({x},{y}): {e}")

                # Draw zone boundary
                zone_width = min(zone_size, width - x) * cell_size
                zone_height = min(zone_size, height - y) * cell_size
                draw.rectangle(
                    [
                        x * cell_size,
                        y * cell_size,
                        x * cell_size + zone_width,
                        y * cell_size + zone_height,
                    ],
                    fill=None,
                    outline="#FFD700",  # gold border for zone
                    width=2,
                )

        # Convert to bytes
        buffer = io.BytesIO()
        img.save(buffer, format="PNG")
        img.save("current_frame.png", format="PNG")  # Save for debugging
        buffer.seek(0)  # Reset buffer position
        return buffer.getvalue()

    def convert_action_text_to_game_action(
        self, action_text: str, reason: str = ""
    ) -> GameAction:
        """Convert action text to GameAction object."""
        action_text = action_text.strip().upper()
        if action_text == "W":
            action = GameAction.ACTION1
        elif action_text == "A":
            action = GameAction.ACTION2
        elif action_text == "S":
            action = GameAction.ACTION3
        elif action_text == "D":
            action = GameAction.ACTION4
        elif action_text == "SPACE":
            action = GameAction.ACTION5
        elif action_text == "RESET":
            action = GameAction.RESET
        elif action_text.startswith("CLICK(") and action_text.endswith(")"):
            coords = action_text[6:-1].split(",")
            if len(coords) == 2:
                x, y = map(int, coords)
                action = GameAction.ACTION6
                action.set_data(
                    data={
                        "x": x,
                        "y": y
                    }
                )
        else:
            logger.warning(f"Unknown action text: {action_text}")
            return GameAction.RESET
        action.reasoning = {
            "desired_action": f"{action.value}",
            "reason": reason if reason else "No specific reason provided"
        }
        return action

    def convert_game_action_to_text(
        self, action: GameAction
    ) -> str:
        """Convert GameAction to text representation."""
        if action == GameAction.ACTION1:
            return "W"
        elif action == GameAction.ACTION2:
            return "A"
        elif action == GameAction.ACTION3:
            return "S"
        elif action == GameAction.ACTION4:
            return "D"
        elif action == GameAction.ACTION5:
            return "SPACE"
        elif action == GameAction.RESET:
            return "RESET"
        elif action == GameAction.ACTION6:
            data = action.action_data
            return f"CLICK({data.x},{data.y})"
        else:
            logger.warning(f"Unknown GameAction: {action}")
            return "UNKNOWN"

    def do_random_hypothesis_analysis(self, frames: List[FrameData]) -> str:
        """Perform random hypothesis analysis on the frames."""
        logger.info("Performing random hypothesis analysis on frames...")

        # generate unique file name for video
        video_file_name = f"random_hypothesis_analysis_{frames[0].game_id}.mp4"
        video_file_path = os.path.join("recordings", video_file_name)
        self.generate_video_from_scorecard = self.generate_video_from_grids(
            frames=frames,
            video_output_path=video_file_path,
            fps=self.RANDOM_ANALYSIS_FPS,
            skip_repeated_frames=self.RANDOM_ANALYSIS_SKIP_REPEATED_FRAMES_FLAG,
        )
        video_bytes = open(video_file_path, 'rb').read()

        random_explorer_agent_response = self.gemini_client.models.generate_content(
            model=self.RANDOM_ANALYSIS_MODEL,
            contents=types.Content(
                parts=[
                    types.Part(
                        inline_data=types.Blob(data=video_bytes, mime_type='video/mp4')
                    ),
                    types.Part(text=RANDOM_HYPOTHESIS_ANALYSIS_PROMPT)
                ]
            )
        )
        
        self.track_tokens(
            random_explorer_agent_response.usage_metadata.total_token_count, random_explorer_agent_response.text
        )
        all_random_hypothesis_text = random_explorer_agent_response.text.strip()
        logger.info(f"Random analysis completed: {all_random_hypothesis_text}")
        return all_random_hypothesis_text


    def generate_video_from_grids(
        self,
        frames: list[FrameData],
        video_output_path="output_video.mp4",
        pixel_size=10,
        fps=10,
        skip_repeated_frames=False,
    ) -> None:
        # === Color palette (from key_colors as hex) ===
        key_colors = {
            0: "#FFFFFF", 1: "#CCCCCC", 2: "#999999", 3: "#666666",
            4: "#333333", 5: "#000000", 6: "#E53AA3", 7: "#FF7BCC",
            8: "#F93C31", 9: "#1E93FF", 10: "#88D8F1", 11: "#FFDC00",
            12: "#FF851B", 13: "#921231", 14: "#4FCC30", 15: "#A356D6"
        }

        # Convert to BGR for OpenCV
        palette = np.array(
            [tuple(int(color[i:i+2], 16) for i in (1, 3, 5))[::-1] for color in key_colors.values()],
            dtype=np.uint8
        )

        # === Determine frame size from first frame ===
        first_grid = frames[0].frame[0]
        h, w = len(first_grid), len(first_grid[0])
        frame_size = (w * pixel_size, h * pixel_size)

        # === Setup video writer ===
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        video = cv2.VideoWriter(video_output_path, fourcc, fps, frame_size)

        # === Frame processing loop with deduplication ===
        prev_frame = None
        for frame in frames:
            if skip_repeated_frames and self.is_frames_equal(prev_frame, frame):
                logger.debug("Skipping duplicate frame")
                continue  # Skip duplicate frame
            prev_frame = frame

            for grid in frame.frame:
                grid_array = np.array(grid, dtype=np.uint8)
                color_image = palette[grid_array]  # shape: (H, W, 3)
                scaled_image = cv2.resize(color_image, frame_size, interpolation=cv2.INTER_NEAREST)
                video.write(scaled_image)

        video.release()
        print(f"✅ Video saved to {video_output_path}")

    def retrieve_top_hypothesis(self, all_random_hypothesis_text: str) -> str:
        """Retrieve the top hypothesis from the random analysis response."""
        prompt = TOP_HYPOTHESIS_RETRIEVER_PROMPT.format(
            all_random_hypothesis_text=all_random_hypothesis_text
        )
        messages = [
            {
                "role": "user",
                "content": prompt,
            }
        ]

        response = self.client.chat.completions.create(
            model=self.TOP_HYPOTHESIS_GENERATOR_MODEL,
            messages=messages,
            # reasoning_effort="low",
        )
        
        self.track_tokens(
            response.usage.total_tokens, response.choices[0].message.content
        )
        self.capture_reasoning_from_response(response)

        top_hypothesis = response.choices[0].message.content
        logger.info(f"Top hypothesis retrieved: {top_hypothesis}")
        return top_hypothesis
